[package]
name = "lunatic"
version = "0.7.0"
edition = "2018"
authors = ["Bernard Kolobara <bernard@lunatic.solutions>"]
description = "This library contains higher level wrappers for low level Lunatic syscalls."
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde_messagepack", "serde_json"]
serde_messagepack = ["rmp-serde"]

[dependencies]
thiserror = "1.0"
lunatic-macros = { version = "^0.6.1", path = "./lunatic-macros" }

serde = { version = "1.0", features = ["derive"]}
rmp-serde = { version = "0.15", optional = true }
serde_json = { version = "1.0.66", optional = true }
bincode = "1.3.3"

[workspace]
members = [
  "lunatic-macros"
]
